services:
  db:
    image: mariadb
    container_name: prog-III-blog-BD
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: prog-III-blog-app
    volumes:
      - ./php:/app
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
